### ISSUE TITLE
BC-break with latest rollbar/rollbar release

### ISSUE THREAD

**Issue by webbertakken** [rollbar/rollbar-php-symfony-bundle#40] opened 2018-10-30 13:43 UTC
BC-break with latest rollbar/rollbar release.

It can be fixed by changing dependency to rollbar/rollbar to max at ~1.6

Cheers

**Comment by jessewgibbs** [comment] 2018-10-30 17:21
@webbertakken thanks for bringing this to our attention.

@ArturMoczulski can you take a look at this?

**Comment by hngl** [comment] 2018-11-05 12:39
@webbertakken What is actually breaking? What error message do you get? Could not deduce that from the release notes of [rollbar/rollbar](https://github.com/rollbar/rollbar-php/releases/tag/v1.7.0).

**Comment by hngl** [comment] 2018-11-05 14:38
Will be fixed by PR #42

**Comment by ArturMoczulski** [comment] 2018-11-12 12:32
This was caused by a bug in `v1.7.0` and has been now resolved with the `rollbar/rollbar-php:v1.7.0` release. Please run `composer update` in you Symfony app to update to the latest rollbar-php release.

**Closed by ArturMoczulski** 2018-11-12 12:32 UTC
Labels: bug
